remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable support for hyphenated search words:
search_tokenizer_separator: /[\s/]+/

# Color scheme currently only supports "dark" or nil (default)
color_scheme: "dark"
